### ISSUE TITLE
Looking forward to your great work

### ISSUE THREAD

**Issue by hmyao22** [yeyimilk/transfer-contrastive-learning#1]
Dear author, congratulations on the acceptance of your article. I hope you can publish the complete data and code as soon as possible.

**Comment by yeyimilk** [comment]
Hi, the full code has been updated, but I am not supposed to release the original data for Ramen data due to HIPAA, so I generate random data to replace it. I will try to use GAN to create similar data and replace the random data later. Feel free to let me know if you have any questions.
